"""Generate docs/rlpy-api-reference.md from Character Creator 4's SWIG wrapper.

Reads RLPy.py statically (no CC4 needed). Every method entry carries the C++
signature from its SWIG docstring, which is what tells you argument types.

Usage:
    python tools/gen_rlpy_reference.py ["C:/Program Files/Reallusion/Character Creator 4/Bin64/RLPy.py"]
"""

from __future__ import annotations

import ast
import os
import re
import sys
from collections import defaultdict

DEFAULT_SRC = r"C:\Program Files\Reallusion\Character Creator 4\Bin64\RLPy.py"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "rlpy-api-reference.md")


def _sig_lines(doc: str | None) -> list[str]:
    if not doc:
        return []
    return [ln.strip() for ln in doc.strip().splitlines() if "(" in ln and "->" in ln or ln.strip().endswith(")")]


def main() -> None:
    src_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    tree = ast.parse(open(src_path, encoding="utf-8").read())

    classes: list[tuple[str, list[str], list[tuple[str, list[str]]]]] = []
    functions: list[tuple[str, list[str]]] = []
    constants: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            if node.name.startswith("_") or node.name.startswith("Swig"):
                continue
            bases = [b.id for b in node.bases if isinstance(b, ast.Name) and b.id != "object"]
            methods = []
            for item in node.body:
                if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
                    methods.append((item.name, _sig_lines(ast.get_docstring(item))))
            classes.append((node.name, bases, methods))
        elif isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            functions.append((node.name, _sig_lines(ast.get_docstring(node))))
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if re.match(r"^E[A-Za-z0-9]+_", name):
                constants.append(name)

    enums: dict[str, list[str]] = defaultdict(list)
    for c in constants:
        prefix = c.split("_", 1)[0]
        enums[prefix].append(c)

    out: list[str] = [
        "# RLPy API Reference (Character Creator 4)",
        "",
        f"> Generated by `tools/gen_rlpy_reference.py` from `{src_path}`.",
        "> Static read of the SWIG wrapper: signatures come from SWIG docstrings; nothing here was called at runtime.",
        f"> {len(classes)} classes | {len(enums)} enum groups ({len(constants)} values) | {len(functions)} module functions",
        "",
        "## Enums",
        "",
    ]
    for prefix in sorted(enums):
        out.append(f"### {prefix}")
        out.append("")
        out.extend(f"- `{v}`" for v in sorted(enums[prefix]))
        out.append("")

    out += ["## Classes", ""]
    for name, bases, methods in sorted(classes):
        out.append(f"### {name}")
        out.append("")
        if bases:
            out.append(f"**Inherits from:** {', '.join(f'`{b}`' for b in bases)}")
            out.append("")
        for mname, sigs in methods:
            if sigs:
                for s in sigs:
                    out.append(f"- `{s}`")
            else:
                out.append(f"- `{mname}`")
        out.append("")

    out += ["## Module functions", ""]
    for name, sigs in sorted(functions):
        out.extend(f"- `{s}`" for s in sigs) if sigs else out.append(f"- `{name}`")
    out.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.normpath(OUT)}: {len(classes)} classes, {len(constants)} enum values, {len(functions)} functions")


if __name__ == "__main__":
    main()
